[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/games"
  to = "/.netlify/functions/games"
  status = 200

[[redirects]]
  from = "/api/odds"
  to = "/.netlify/functions/odds"
  status = 200
